<section id="further-info">
    <div class="content-wrapper row">
        <h2><span>Traineedagen Göteborg</span><span>more than just a fair</span></h2>
        <div class="col-sm-8 col-sm-offset-2">
            <p>A fair for Trainee programs alone will be realized for the first time in Gothenburg this autumn at Chalmers University of Technology. Does this make you curious? Do You want to meet the top student in Gothenburg and have them join your Traineeprogram? Make sure to be there 8th of October 2015!</p>
            <p>The Trainee-day of Gothenburg will create an opportunity for highly reputable companies to present their Trainee program to Gothenburgs best students, according to the company’s preferences. During the Trainee-day of Gothenburg there will be 20 spots for exhibitors and 200 students from Chalmers University of Technology, Gothenburgs University and the IT University. The students will apply to participate and a selection of the most qualified will be made. Our goal is to provide a perfect mix of different personalities and competences that will match your company’s expectations.</p>
            <p>The fair provides an opportunity to meet and interact with students in a more personal environment, not only during the fair but also through interview simulations and company presentations/workshops. The day is rounded off with a buffet and some casual activites, for example ping-pong.</p>
            <p>Can you afford to miss this? Acando and Eon is already with us, these companies are investing in the future, will you?</p>
        </div>
    </div>
</section>