<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="sv-SE" class="no-js">
<head>
    <title>Traineedagen Göteborg | Chalmers Studentkår Promotion</title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="icon" href="<?php bloginfo('stylesheet_directory') ?>/static/images/icon.ico/favicon.ico?v=1.1" type="image/x-icon">
    <meta name="viewport" content="initial-scale=1" />

    <link href='<?php bloginfo('stylesheet_directory') ?>/static/css/fonts/avenir/avenir.css' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php bloginfo('stylesheet_directory') ?>/fullPage.css">
    <link rel="stylesheet" type="text/css" media="screen" href="http://chspromotion.se/wp/wp-content/themes/chsp/css/styles.css">
    <link rel="stylesheet" type="text/css" media="screen" href="http://chspromotion.se/wp/wp-content/themes/chsp/css/responsive.css">
    <link href='<?php bloginfo('stylesheet_directory') ?>/style.css' rel='stylesheet' type='text/css'>
    <link href='<?php bloginfo('stylesheet_directory') ?>/traineedagen.css' rel='stylesheet' type='text/css'>

    <meta property="og:title" content="Traineedagen Göteborg | Chalmers Studentkår Promotion" />
    <meta property="og:description" content="We want to create an exclusive Trainee fair where both companies and students with the right competence, features and skills will interact. Our ambition is to make the perfect match between both parties." />
    <meta property="og:image" content="http://chspromotion.se/traineedagen/wp-content/themes/eday/images/facebooklogga-01.png" />

    <!--[if lt IE 9]>
    <script>
        document.createElement('header');
        document.createElement('nav');
        document.createElement('footer');
        document.createElement('article');
    </script>
    <![endif]-->
</head>
<body>


<div id="index">