<header>
    <div class="title-container">
        <img src="<?php bloginfo('stylesheet_directory') ?>/static/images/traineedagengoteborgvit.png" height="125" />
        <p class="notice-important" style="margin:60px 0 12px !important;display:none;">8 oktober 2015</p>
        <h1 style="
		  margin-top: 40px;
  text-align: right;
  width: 531px;
  ">October 8th, 2015</h1>
    </div>
    <div class="title-shape-wrapper">
        <div class="title-interaction title-interaction-first">
            <a class="scroll-to" data-target="schedule"><span>Schedule</span></a>
        </div>
        <div class="title-interaction">
            <a class="scroll-to" data-target="participation"><span>Participation</span></a>
        </div>
        <div class="title-shape"></div>
    </div>

    <div class="fa fa-chevron-down scroll-to" id="navigate-down" data-target="main-content"></div>
</header>

<div class="wrapper" id="main-content">