
<section class="dark">
    <div class="content-wrapper row">
        <div class="col-sm-6">
            <div class="page-title"><span class="highlight">Interact</span> and <span>connect</span></div>
        </div>
        <div class="col-sm-6 intro-text">
            <p>We want to create an exclusive Trainee fair where both companies and students with the right competence,
                features and skills will interact. Our ambition is to make the perfect match between both parties.</p>

        </div>
    </div>
</section>