<section id="participation" style="
    background-image: url('http://chspromotion.se/eday/wp-content/themes/eday/images/cloud.jpg');
    background-size: cover;
    background-position: center center;
    position:relative;
">
    <div style="
	position:absolute;
	width:100%;
	height:100%;
	top:0;
	left:0;
	z-index:2;
	background:rgba(11,11,11,0.8);
	"></div>
    <div class="content-wrapper" style="position:relative;z-index:3;">
        <div class="offer-title" style="color:white;">Participation</div>
        <div class="row">
            <div class="col-sm-4 offer">
                <div>
                    <h3>Before Fair</h3>
                    <p><strong style="font-weight:900">Interview simulation:</strong>
                        An opportunity for your company to interact and also test the students. Furthermore, an opportunity for students to participate in a simulated interview/case as well as receive feedback. Two breakfast tickets and lunch tickets are included, more can be ordered.
                    </p>
                </div>
            </div>
            <div class="col-sm-4 offer">
                <div>
                    <h3>Fair</h3>
                    <p><strong style="font-weight:900">Stand (Included in standard package)</strong>
                        The fair will be limited to 20 companies, and hence 20 stands. Every company will have access to 5 square metres of exhibition booth or display, in the exhibition area and access to a table and Internet connection. An additional 5 square metres can be added. The fair will last for 4 hours which means many student per time unit.
                    </p>
                    <p><strong style="font-weight:900">Company presentation/workshop</strong>
                        An opportunity to market and sell your company to the students. The time is limited to 20 minutes and can be used however the company chooses. Either a company presentation can be made or a workshop, or of course a mix of both. </p>
                </div>
            </div>
            <div class="col-sm-4 offer">
                <div>
                    <h3>After Fair</h3>
                    <p><strong style="font-weight:900">Mingle in the evening with a buffet (Included in standard package)</strong>
                        Food and drinks in a more relaxed environment but still at the Student unions house. There is also room for activities during this part of the day such as for example Ping-Pong. Two dinnertickets are included in the standard package, more can be ordered. </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="offer-title" style="color:white;  padding-top: 60px;">The Marketing Channels</div>
            <div class="col-md-4 col-md-offset-2 col-sm-5 col-sm-offset-1 offer">
                <div>
                    <h3>Included in the standard package</h3>

                    <p><strong style="font-weight:900">Marketing of the Trainee-day</strong>
                        All companies will be exposed when marketing the Trainee-day.</p>

                    <p><strong style="font-weight:900">One day exposure through our social media channels</strong>
                        Every company will receive one private day of exposure through our social media channels.</p>

                    <p><strong style="font-weight:900">Exposure at traineedagengbg.se</strong>
                        Traineedagengbg.se is the webpage for the Trainee-day of Gothenburg. All companies will be exposed here before, during and after the fair.</p>

                    <p><strong style="font-weight:900">Traineedagskatalogen</strong>
                        A catalogue about the Trainee-day will be done and sent per post to all accepted students. In the catalogue there will be information about all participating companies as well as their logotype. Every company will get one page each where they can present their Trainee program and company.</p>

                    <p><strong style="font-weight:900">Three universities in Gothenburg</strong>
                        Every company will be exposed at Chalmers University of Technology, Gothenburg’s school of business, economics and law as well as the IT University in Gothenburg.</p>
                </div>
            </div>

            <div class="col-md-4 col-sm-5 offer">
                <div>
                    <h3>Not included in the standard package</h3>

                    <p><strong style="font-weight:900">CORETV</strong>
                    Strategically placed TV-screens at Chalmers unions house. They are seen by thousands of students every day. The screens are used to provide students with vital information.</p>

                    <p><strong style="font-weight:900">Personal mail to all participating students</strong>
                    A personal mail from your company which will be sent by e-mail to all participating students. The company makes the e-mail and we send it to the students. This is an opportunity for your company to decide and formulate exactly what you want the students to know and expect from your company.</p>

                </div>
            </div>

        </div>
</section>