<section class="dark" id="schedule">
    <div class="content-wrapper">
        <div class="time-heading">
            <span>Before Fair</span>
            <div>08:00 - 11:30</div>
        </div>

        <div class="timetable row">
            <div class="col-sm-7">
                <div class="timed-event">
                    <div class="event-time">08:00 - 11:30 @ Volvofoajén</div>
                    <div class="event-text">Interview simulation</div>
                </div>

                <div class="clear"></div>
            </div>
            <div class="col-sm-5">
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <div id="timetable-line"></div>
        </div>
</section>

<section class="dark" id="schedule" style="padding-top:0;">
    <div class="content-wrapper">
        <div class="time-heading">
            <span>Fair</span>
            <div>12:30 - 17:00</div>
        </div>

        <div class="timetable row">
            <div class="col-sm-7">
                <div class="timed-event">
                    <div class="event-time">13:00 - 13:30 @ Volvofoajén</div>
                    <div class="event-text">Company #1</div>
                </div>
                <div class="timed-event">
                    <div class="event-time">13:30 - 14:00 @ Volvofoajén</div>
                    <div class="event-text">Company #2</div>
                </div>
                <div class="timed-event">
                    <div class="event-time">14:00 - 14:30 @ Volvofoajén</div>
                    <div class="event-text">Company #5</div>
                </div>
                <div class="timed-event">
                    <div class="event-time">14:30 - 15:00 @ Volvofoajén</div>
                    <div class="event-text">Company #4</div>
                </div>
                <div class="timed-event">
                    <div class="event-time">15:00 - 15:30 @ Volvofoajén</div>
                    <div class="event-text">Company #5</div>
                </div>
                <div class="timed-event">
                    <div class="event-time">15:30 - 16:00 @ Volvofoajén</div>
                    <div class="event-text">Company #6</div>
                </div>
                <div class="timed-event">
                    <div class="event-time">16:00 - 16:30 @ Volvofoajén</div>
                    <div class="event-text">Company #7</div>
                </div>
                <div class="timed-event">
                    <div class="event-time">16:30 - 17:00 @ Volvofoajén</div>
                    <div class="event-text">Company #8</div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="col-sm-5">
                <div class="day-event" style="height:auto">
                    <div class="event-text" style="width:100%;position:static;margin-top:0;">
                        <div class="event-time">12:30 - 13:00 @ Runan</div>
                        <div class="event-text">Inspirational lecture</div>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div class="day-event" style="height:auto">
                    <div class="event-time">13:00 - 17:00 @ Volvofoajén</div>
                    <div class="event-text" style="width:100%;position:relative;margin-top:0;">

                        <div style="  margin-top: 23px;">
                        Exhibition area<br />
                            - Stand location<br />
                            - Student/company lounge with refreshments
                            </div>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div class="day-event" style="height:auto">
                    <div class="event-time">13:00 - 17:00 @ Volvofoajén</div>
                    <div class="event-text" style="width:100%;position:static;margin-top:0;">
                        <div style="  margin-top: 23px;">Company presentation and workshop</div>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <div id="timetable-line"></div>
        </div>
</section>

<section class="dark" id="schedule" style="padding-top:0;">
    <div class="content-wrapper">
        <div class="time-heading">
            <span>After Fair</span>
            <div>17:00 - Late</div>
        </div>

        <div class="timetable row">
            <div class="col-sm-7">
                <div class="timed-event">
                    <div class="event-time">18:00 - 19:30 @ Scaniasalen</div>
                    <div class="event-text">Buffet</div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="col-sm-5">
                <div class="day-event" style="height:auto">
                    <div class="event-time">17:00 - @ Scaniasalen</div>
                    <div class="event-text" style="width:100%;position:static">
                        Mingle & Activities
                    </div>
                    <div style="clear:both"></div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <div id="timetable-line"></div>
        </div>
</section>